# NumPy Arrays

In [2]:
import numpy as np

In [3]:
# lista
mylist = [1, 2, 3]
mylist

[1, 2, 3]

In [4]:
# criando array numpy
np.array(mylist)

array([1, 2, 3])

In [5]:
nested_list = [[1,2], [3,4], [5,6]]
nested_list


[[1, 2], [3, 4], [5, 6]]

In [6]:
# numpy array de nested list
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Built-in Methods

### arange

In [7]:
# np.arange(start, stop, step, dtype) [x, y)
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# step = 2
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### zeros and ones

Generate arrays of zeros or ones. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [9]:
# cria matriz de zeros
np.zeros(3)

array([0., 0., 0.])

In [10]:
# inserindo o shape
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
# matriz de '1'
np.ones(2)

array([1., 1.])

In [12]:
# shape
np.ones((3,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### linspace 
Return evenly spaced numbers over a specified interval. [[reference](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [13]:
# np.linspace(start, stop, interval) [intervalos fechados]
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [14]:
# inclui o stop point, atenção para adicionar uma unidade pro intervalo ficar simétrico
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [15]:
# matriz identidade
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 
Numpy also has lots of ways to create random number arrays:

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [16]:
# cria um array com valores aleatórios e o shape atribuido, entre [0, 1)
np.random.rand(2)

array([0.58226707, 0.91253863])

In [17]:
# matriz
np.random.rand(3, 4)

array([[0.0506846 , 0.48494793, 0.09028288, 0.36551341],
       [0.54857678, 0.15455569, 0.86554708, 0.79981376],
       [0.03335651, 0.43439735, 0.95360339, 0.34201717]])

### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [18]:
# mesma função acima, mas seguindo uma distribuição normal: média = 0 e variÂncia = 1
np.random.randn(5, 5)

array([[ 0.70839788,  0.11055464, -0.08491701, -0.65134729, -1.47462176],
       [-0.42359328, -0.46624938,  0.34634469,  0.38874156,  1.42505134],
       [-0.04008864,  1.02645358, -1.54664141,  2.09803768, -0.53413803],
       [ 2.64040497,  0.21577249,  0.87000476,  0.16269551, -0.55322481],
       [ 0.99185073, -0.03665245,  0.45833328, -1.59673539,  0.14793386]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [19]:
# um inteiro entre [1, 100)
np.random.randint(1,100)

22

In [20]:
# 10 números inteiros
np.random.randint(1,100,10)

array([35, 50, 16, 14, 37, 90, 87, 66, 61, 71])

In [21]:
# matriz
np.random.randint(1,100,(3, 5))

array([[17, 50, 60, 28, 72],
       [41, 95, 32, 33, 12],
       [76, 41, 88, 45, 18]])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [22]:
# lançando uma semente, sempre teremos o mesmo resultado, para que possa ser replicado
# deve estar na mesma célula para funcionar 
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [23]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [24]:
# criando dois arrays
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## Reshape
Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [27]:
# reorganiza o array
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [28]:
# valor máximo
ranarr.max()

39

In [29]:
# mínimo 
ranarr.min()

2

In [30]:
# posição do mínimo
ranarr.argmin()

9

In [31]:
# posição do máximo
ranarr.argmax()

7

### dtype

You can also grab the data type of the object in the array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [32]:
# tipo de dados
ranarr.dtype

dtype('int64')

In [33]:
myarr = np.random.rand(2)
myarr.dtype

dtype('float64')