# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
arr[8]

8

In [5]:
# selecionando uma fração do array [x,y)
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
# até o fim
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# alterando os 5 primeiros valores
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
# recriando
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# array apenas com uma fatia do arr original
slice_of_arr = arr[0:5]

In [19]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# alterando valores
slice_of_arr[:] = 99

In [22]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [23]:
# com a biblioteca NUMPY, também altera o array original
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [24]:
# se não quiser alterar o array original, tem que explicitar que é uma cópia
arr_copy = arr.copy()

In [25]:
arr_copy[:] = 100

In [26]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [27]:
# neste caso, não altera
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend using the comma notation for clarity.

In [28]:
# criando matriz numpy
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
arr_2d.shape

(3, 3)

In [33]:
# slecionando a primeira linha
arr_2d[0:1,:]

array([[ 5, 10, 15]])

In [35]:
# da mesma maneira
arr_2d[0]

array([ 5, 10, 15])

In [36]:
arr_2d[2]

array([35, 40, 45])

In [37]:
# um elemento
arr_2d[1,1]

25

In [38]:
# ou assim
arr_2d[1][1]

25

In [39]:
# uma seção da matriz
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

## Conditional Selection

This is a very fundamental concept that will directly translate to pandas later on, make sure you understand this part!

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [40]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
# apenas os maiores que 4 
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [43]:
# array booleano
bool_arr = arr>4

In [44]:
# podemos usar como filtro
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [45]:
# em apenas um passo
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])