# NumPy Arrays

In [3]:
import numpy as np

In [6]:
# lista
mylist = [1, 2, 3]
mylist

[1, 2, 3]

In [7]:
# criando array numpy
np.array(mylist)

array([1, 2, 3])

In [8]:
nested_list = [[1,2], [3,4], [5,6]]
nested_list


[[1, 2], [3, 4], [5, 6]]

In [9]:
# numpy array de nested list
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Built-in Methods

### arange

In [10]:
# np.arange(start, stop, step, dtype) [x, y)
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# step = 2
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### zeros and ones

Generate arrays of zeros or ones. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [12]:
# cria matriz de zeros
np.zeros(3)

array([0., 0., 0.])

In [16]:
# inserindo o shape
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
# matriz de '1'
np.ones(2)

array([1., 1.])

In [18]:
# shape
np.ones((3,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### linspace 
Return evenly spaced numbers over a specified interval. [[reference](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [21]:
# np.linspace(start, stop, interval) [intervalos fechados]
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [23]:
# inclui o stop point, atenção para adicionar uma unidade pro intervalo ficar simétrico
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [24]:
# matriz identidade
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 
Numpy also has lots of ways to create random number arrays:

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [25]:
# cria um array com valores aleatórios e o shape atribuido, entre [0, 1)
np.random.rand(2)

array([0.62218767, 0.97446624])

In [26]:
# matriz
np.random.rand(3, 4)

array([[0.03704339, 0.73464856, 0.13204644, 0.99424426],
       [0.42062821, 0.7161721 , 0.92340129, 0.36747603],
       [0.11677075, 0.15573873, 0.98618956, 0.69953155]])

### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [27]:
# mesma função acima, mas seguindo uma distribuição normal: média = 0 e variÂncia = 1
np.random.randn(5, 5)

array([[-0.06300049, -1.59732971, -0.04791037, -0.41891192, -0.98052304],
       [ 0.40122033, -0.78430927,  1.28768034,  1.55859332,  1.37487041],
       [ 1.21742429,  1.32153518, -0.24180817, -0.102458  , -0.14489818],
       [-0.56451682,  0.69951233,  1.08488835,  0.22394358,  0.83867097],
       [-0.54682053,  0.3387173 , -0.18117732, -0.33291384, -1.81830339]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [28]:
# um inteiro entre [1, 100)
np.random.randint(1,100)

71

In [29]:
# 10 números inteiros
np.random.randint(1,100,10)

array([11, 30, 87, 71, 14, 85, 55,  8, 82, 29])

In [30]:
# matriz
np.random.randint(1,100,(3, 5))

array([[ 2,  3, 23, 26, 16],
       [63, 99, 39, 24, 46],
       [81, 65, 66, 33, 37]])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [32]:
# lançando uma semente, sempre teremos o mesmo resultado, para que possa ser replicado
# deve estar na mesma célula para funcionar 
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [33]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [34]:
# criando dois arrays
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## Reshape
Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [43]:
# reorganiza o array
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [44]:
# valor máximo
ranarr.max()

39

In [46]:
# mínimo 
ranarr.min()

2

In [47]:
# posição do mínimo
ranarr.argmin()

9

In [48]:
# posição do máximo
ranarr.argmax()

7